server:
  port: 7004
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: gateway7004

  cloud:
    gateway:
      # ???????????????????????????
      routes:
        # ??????????????
        - id: gateway-provider_1
          # ?????????????
          uri: http://localhost:7003
          # ????
          predicates:
            # Path Route Predicate Factory ????? /gateway/provider/** ??????????? http://localhost:9024 ??uri?
            - Path=/gateway/consumer/**
            # Weight Route Predicate Factory ???????????????????????80%
            # ???group1?????????????
            - Weight=group1, 8
          # ?????????
          filters:
            # StripPrefix????????????1?????/gateway
            - StripPrefix=1

        - id: gateway-provider_2
          uri: http://localhost:7003
          # ????
          predicates:
            - Path=/gateway/consumer/**
            # Weight Route Predicate Factory?????????????????????20%
            - Weight=group1, 2
          # ?????????
          filters:
            # StripPrefix????????????1?????/gateway
            - StripPrefix=1

